export enum MockFileNames {
  NAVIGATION_WITH_MULTIPLE_NESTING = "navigation-with-multiple-nesting.mock",
  NAVIGATION_WITH_ONE_NESTING = "navigation-with-one-nesting.mock",
  DASHBOARD_META = "dashboard.mock",
  SALES_META = "sales.mock",
  PRODUCTS_META = "products.mock",
  CUSTOMERS_META = "customers.mock",
  LAST_10_DAYS_REVENUE = "last-10-day-revenue.mock",
  TOP_PRODUCTS = "top-10-products.mock",
  TOP_CUSTOMERS = "top-10-customers.mock",
  DASHBOARD_CARDS = "dashboard-summary-cards.mock",
  SALES_CARDS = "sales-cards.mock",
  SALES_METRICS = "sales-metrics.mock",
  SALES_REVENUE_PROFIT = "sales-revenue-profit.mock",
  PRODUCTS_CARDS = "products-cards.mock",
  PRODUCTS_METRICS = "products-metrics.mock",
  CUSTOMERS_CARDS = "customers-cards.mock",
  CUSTOMERS_METRICS = "customers-metrics.mock",
  HOURLY_SALES_TREND = "sales-trend.mock",
}
